exclude: 'vendor/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [ python ]
      - id: end-of-file-fixer
        types: [ python ]
      - id: check-docstring-first
        types: [ python ]
      - id: detect-private-key

# Disabling black due to weird behavior around formatting string literals
#  - repo: https://github.com/psf/black
#    rev: 23.11.0
#    hooks:
#      - id: black

  # Note: Noqa has been added for functions that already exceed max complexity.
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-length ]

ci:
  autofix_prs: false
