name: Feature Request
description: Request a new feature or change
title: "Feature: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for thinking about, how to evolve depscan.
        Please also search the [issues](https://github.com/owasp-dep-scan/dep-scan/issues) first before submitting a new one.

  - type: textarea
    id: request-description
    attributes:
      label: Request Description
      description: |
        Tell us what should be improved/added/changed/removed and why you think it's necessary.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: |
        Include here any additional information, which you think are relevant to this request.
    validations:
      required: false
