version: 2

build:
    os: ubuntu-22.04
    tools:
        nodejs: "20"
    commands:
        - cd ./documentation && npm i && cd ..
        - cd ./documentation && npm run build && cd ..
        - cd ./documentation && mv ./.docusaurus/* $READTHEDOCS_OUTPUT/html

