version: 2

build:
    os: ubuntu-22.04
    tools:
        nodejs: "22"
    jobs:
        post_install:
            # - npm --prefix ./documentation i ./documentation
            - npm i
            - npm run build
            - mv ./.docusaurus/* $READTHEDOCS_OUTPUT/html

