version: 2

build:
    os: ubuntu-22.04
    tools:
        nodejs: "20"
    jobs:
        post_install:
            - cd ./documentation && npm i && cd ..
            - cd ./documentation && npm run build && cd ..
            - cd ./documentation && mv ./.docusaurus/* $READTHEDOCS_OUTPUT/html

