name: docker tests

on:
  push:
    branches:
      - master
      - feature/*
    paths-ignore:
      - '**/README.md'
  pull_request:
jobs:
  version_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[dev]
        npm install -g @cyclonedx/cdxgen
        mkdir -p repotests
#    - name: VDB
#      if: matrix.os != 'windows-latest'
#      run: |
#        rm -rf $VDB_HOME && mkdir -p $VDB_HOME
#      env:
#        VDB_HOME: "vdb_data"
    - name: Run pytest tests
      run: |
        python3 -m pip install -r contrib/requirements.txt
        python3 -m pytest test
      env:
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VDB_HOME: "vdb_data"
    - name: Test container images
      run: |
        mkdir -p containertests_${{ matrix.os }}_python${{ matrix.python-version }}
        # python3 depscan/cli.py --no-banner --cache --no-error --src ghcr.io/owasp-dep-scan/dep-scan -o containertests_${{ matrix.os }}_python${{ matrix.python-version }}/depscan-scan.json -t docker
        python3 depscan/cli.py --no-banner --cache --no-error --src shiftleft/scan-slim -o containertests_${{ matrix.os }}_python${{ matrix.python-version }}/depscan-slim.json -t docker,license --no-vuln-table
        python3 depscan/cli.py --no-banner --no-error --src redmine@sha256:a5c5f8a64a0d9a436a0a6941bc3fb156be0c89996add834fe33b66ebeed2439e -o containertests_${{ matrix.os }}_python${{ matrix.python-version }}/depscan-redmine.json -t docker --no-vuln-table
      env:
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VDB_HOME: "vdb_data"
    - uses: actions/upload-artifact@v1
      with:
        name: containertests_${{ matrix.os }}_python${{ matrix.python-version }}
        path: containertests_${{ matrix.os }}_python${{ matrix.python-version }}
  version_tests2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[dev]
        npm install -g @cyclonedx/cdxgen
        mkdir -p repotests
    - uses: actions/checkout@v4
      with:
        repository: 'GoogleCloudPlatform/microservices-demo'
        path: 'repotests/microservices-demo'
    - uses: actions/checkout@v4
      with:
        repository: 'OWASP/NodeGoat'
        path: 'repotests/NodeGoat'
    - name: Test container images
      run: |
        mkdir -p containertests_${{ matrix.os }}
        python3 -m pip install -r contrib/requirements.txt
        python3 depscan/cli.py --no-banner --no-error --src rocket.chat@sha256:379f7afa0e67497c363ac9a9b3e7e6a6d31deee228233307c987e4a0c68b28e6 -o containertests_${{ matrix.os }}/depscan-rocket.json --no-vuln-table
        python3 depscan/cli.py --no-banner --no-error --src ./test/data/bom-yaml-manifest.json -o containertests_${{ matrix.os }}/depscan-yaml.json --no-vuln-table
        python3 depscan/cli.py --no-banner --no-error --src repotests/microservices-demo -o containertests_${{ matrix.os }}/depscan-msd.json
        python3 depscan/cli.py --no-banner --no-error --src repotests/NodeGoat --reports-dir containertests_${{ matrix.os }}/ng-reports
      env:
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONUTF8: 1
    - uses: actions/upload-artifact@v1
      with:
        name: containertests_${{ matrix.os }}
        path: containertests_${{ matrix.os }}
