name: gobintests tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - 'dockertests.yml'
      - 'pythonapp.yml'
      - 'python-publish.yml'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install .[dev]
        sudo npm install -g @cyclonedx/cdxgen
    - name: Test go binaries
      run: |
        mkdir -p gobintests
        cd gobintests
        wget -q https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
        unzip terraform_1.0.7_linux_amd64.zip
        wget -q https://releases.hashicorp.com/consul/1.10.2/consul_1.10.2_linux_amd64.zip
        unzip consul_1.10.2_linux_amd64.zip
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        rm *.zip
        cd ..
        oras pull ghcr.io/appthreat/vdb:v5 -o $VDB_HOME
        python3 depscan/cli.py --no-error --src gobintests/terraform -o gobintests/depscan-terraform.json -t go
        python3 depscan/cli.py --no-error --src gobintests/consul -o gobintests/depscan-consul.json -t go
        python3 depscan/cli.py --no-error --src gobintests/minikube-linux-amd64 -o gobintests/depscan-minikube.json -t go
      env:
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VDB_HOME: vdb_data
