name: gobintests tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        sudo npm install -g @appthreat/cdxgen
    - name: Test go binaries
      run: |
        mkdir -p gobintests
        cd gobintests
        wget https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
        unzip terraform_1.0.7_linux_amd64.zip
        rm *.zip
        cd ..
        python depscan/cli.py --no-error --cache --src gobintests/terraform -o gobintests/depscan-terraform.json -t go
        ls -ltr gobintests
      env:
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: gobintests
        path: gobintests
