name: gobintests tests

on:
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        sudo npm install -g @appthreat/cdxgen
        sudo npm install -g @ngcloudsec/cdxgen-plugins-bin
    - name: Install oras
      run: |
        curl -LO https://github.com/oras-project/oras/releases/download/v0.16.0/oras_0.16.0_linux_amd64.tar.gz
        mkdir -p oras-install/
        tar -zxf oras_0.16.0_*.tar.gz -C oras-install/
        mv oras-install/oras /usr/local/bin/
        rm -rf oras_0.16.0_*.tar.gz oras-install/
        oras version
    - name: Test go binaries
      run: |
        mkdir -p gobintests
        cd gobintests
        wget -q https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
        unzip terraform_1.0.7_linux_amd64.zip
        wget -q https://releases.hashicorp.com/consul/1.10.2/consul_1.10.2_linux_amd64.zip
        unzip consul_1.10.2_linux_amd64.zip
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        rm *.zip
        cd ..
        oras pull ghcr.io/ngcloudsec/vdb:v1 -o $VDB_HOME
        python depscan/cli.py --no-error --src gobintests/terraform -o gobintests/depscan-terraform.json -t go
        python depscan/cli.py --no-error --src gobintests/consul -o gobintests/depscan-consul.json -t go
        python depscan/cli.py --no-error --src gobintests/minikube-linux-amd64 -o gobintests/depscan-minikube.json -t go
        ls -ltr gobintests
      env:
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VDB_HOME: vdb_data
